##########################################################################
#공유
commonName: navie
service:
  port: 80
sellectLabels: navie-app
##########################################################################

##########################################################################
# svc
svc:
  name: navie-svc
  type: NodePort
##########################################################################

##########################################################################
#deployment 
deployName: navie-deploy
deployReplicaCount: 1
image:
  repository: 191635887465.dkr.ecr.ap-northeast-2.amazonaws.com/navie
  pullPolicy: IfNotPresent #전략에 따라 Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "47063" #임시로 해놓은 v1, latest가 전략에 따라 효과적
Serviceconnection: allow-secretmanager-fors3upload
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 1
##########################################################################

##########################################################################

# HPA
hpa:
  enabled: true
  name: my-hpa
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
##########################################################################

##########################################################################
#ingress
ingressName: navie-in
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "navie-eks"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/stickiness-enabled: "true"
    alb.ingress.kubernetes.io/target-group-attributes: "stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=300"
    external-dns.alpha.kubernetes.io/hostname: "navie.world"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:191635887465:certificate/f1c8c134-6c06-41be-b991-cc576e382595
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  tls: []
##########################################################################
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
spec:
  selector:
    app: navie-app
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
