apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  labels:
    app: {{ .Values.sellectLabels }}
    project: {{ .Values.commonName }}
  namespace: {{ .Values.commonName }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: {{ .Values.sellectLabels }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}